# This file contains everything for running Kafka and Kafka Manager on Kubernetes
---
apiVersion: v1
kind: List
items:
# Zookeeper
  - apiVersion: v1
    kind: Service
    metadata:
      name: zookeeper
    spec:
      selector:
        name: zookeeper
      ports:
        - port: 2181
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: zookeeper
    spec:
      serviceName: zookeeper
      selector:
        matchLabels:
          name: zookeeper
      template:
        metadata:
          labels:
            name: zookeeper
        spec:
          imagePullSecrets:
            - name: docker-registry
          containers:
            - name: zookeeper
              image: &dockerTag dsmaher/zookeeper:3.4.10
              imagePullPolicy: Always
              ports:
                - containerPort: 2181

# Kafka
  - apiVersion: v1
    kind: Service
    metadata:
      name: kafka
    spec:
      selector:
        name: kafka
      ports:
        - port: 9092
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: kafka
    spec:
      serviceName: kafka
      selector:
        matchLabels:
          name: kafka
      template:
        metadata:
          labels:
            name: kafka
        spec:
          imagePullSecrets:
            - name: docker-registry
          containers:
            - name: kafka
              image: dsmaher/kafka:0.10.2
              imagePullPolicy: Always
              env:
                - name: ZK_CONNECT
                  value: zookeeper:2181
                - name: KAFKA_ADVERTISED_HOST_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              ports:
                - containerPort: 9092

# Kafka Manager
  - apiVersion: v1
    kind: Service
    metadata:
      name: kafka-manager
    spec:
      selector:
        name: kafka-manager
      ports:
        - port: 9000

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: kafka-manager
    spec:
      selector:
        matchLabels:
          name: kafka-manager
      template:
        metadata:
          labels:
            name: kafka-manager
        spec:
          imagePullSecrets:
            - name: docker-registry
          containers:
            - name: kafka-manager
              image: &dockerTag dsmaher/kafka-manager:1.3.3.4
              imagePullPolicy: Always
              ports:
                - containerPort: 9000
              env:
                - name: ZK_HOSTS
                  value: zookeeper:2181

